package com.eos.b2c.ui.action;

import com.eos.accounts.data.RoleType;

public enum PartnerAction implements IAction {

    NONE, //

    LIST_PRODUCT, //
    SAVE_PARTNER_LEAD, //

    PARTNER_CONFIGS(RoleType.ADMIN), //
    PARTNER_CONFIG(RoleType.ADMIN), //
    SAVE_PARTNER_CONFIG(RoleType.ADMIN), //

    CONFIGURE_PROFILE(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRLINE, RoleType.TOUR_OPERATOR, RoleType.AIRPORT, RoleType.TOURISM_BOARD, RoleType.TRAVEL_AGENT),
    SAVE_CONFIGURE_PROFILE(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRLINE, RoleType.TOUR_OPERATOR, RoleType.AIRPORT, RoleType.TOURISM_BOARD, RoleType.TRAVEL_AGENT),
    SELECT_HOTEL(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    HOTEL_LEADS(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT),
    UPDATE_HOTEL_LEAD(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT),
    MANAGE_HOTEL(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.CALLCENTER, RoleType.ADMIN),
    EDIT_HOTEL(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.CALLCENTER, RoleType.ADMIN),
    MANAGE_INVENTORY(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    ADD_INVENTORY(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    MAP_HOTEL(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    ROOM_PACKAGES(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    PUBLISH_FIXED_PACKAGE(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR),
    PUBLISH_ACTIVITY_PACKAGE(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    PUBLISH_HOTEL_PACKAGE(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.EXPERT, RoleType.TRAVEL_AGENT),
    PUBLISH_ITINERARY(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.EXPERT, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT),
    ADD_PACKAGE(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    ADD_PACKAGE_PRICING(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    DELETE_PACKAGE_PRICING(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    DELETE_PACKAGE(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    HOTEL_DEALS(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    AIRLINE_DEALS(RoleType.AIRLINE),
    AIRPORT_DEALS(RoleType.AIRPORT),
    LOAD_HOTEL_DEALS(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    ADD_HOTEL_DEALS(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    LOAD_AIRLINE_DEALS(RoleType.AIRLINE),
    LOAD_AIRPORT_DEALS(RoleType.AIRPORT),
    ADD_AIRLINE_DEALS(RoleType.AIRLINE),
    ADD_AIRPORT_DEALS(RoleType.AIRPORT),
    MANAGE_PACKAGE_PRICING(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    DASHBOARD(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    SEARCH_NOT_FOUND(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    TRENDS(RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    SAVE_RECOMMENDATION(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRLINE, RoleType.TOUR_OPERATOR),
    DELETE_RECOMMENDATION(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRLINE, RoleType.TOUR_OPERATOR),
    DELETE_HOTEL_MAP(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.ADMIN, RoleType.CALLCENTER),
    DELETE_ROOM(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.ADMIN, RoleType.CALLCENTER),
    SAVE_SHOPPINGFLOW(RoleType.AIRLINE, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    SAVE_NEWSHOPPINGFLOW(RoleType.AIRLINE, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    EDIT_RECOMMENDATION(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRLINE, RoleType.TOUR_OPERATOR),
    PUBLISH_HOTEL(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.ADMIN, RoleType.CALLCENTER),
    EDIT_SHOPPINGFLOW(RoleType.AIRLINE, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    PUBLISH_RECOMMENDATIONS(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRLINE, RoleType.TOUR_OPERATOR),
    RECOMMENDATIONS(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRLINE, RoleType.TOUR_OPERATOR),
    OPPORTUNITIES(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRLINE, RoleType.TOUR_OPERATOR),
    HOTEL_PACKAGES(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR),
    ADD_HOTEL_PACKAGE(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR),
    SAVE_HOTEL_PACKAGE(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR),
    DELETE_HOTEL_PACKAGE(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR),
    VIEW_QUESTIONS(RoleType.ADMIN, RoleType.EXPERT, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT),
    EDIT_QUESTION(RoleType.ADMIN),
    ADD_QUESTION(RoleType.ADMIN),
    DELETE_QUESTION(RoleType.ADMIN),
    SHOPPINGFLOWS(RoleType.AIRLINE, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    LOAD_HOTELS(RoleType.ADMIN, RoleType.CALLCENTER),
    LOAD_ALL_HOTELS(RoleType.ADMIN, RoleType.CALLCENTER),
    DOWNLOAD_HOTELS(RoleType.ADMIN, RoleType.CALLCENTER),
    MAP_WEGO_HOTEL(RoleType.ADMIN, RoleType.CALLCENTER),
    ADD_NEW_HOTEL(RoleType.ADMIN, RoleType.CALLCENTER),
    ADD_FRESH_HOTEL(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.GUEST_HOUSE),
    ADD_CONTACT_INFO(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT),
    SAVE_CONTACT_INFO(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT),
    ADD_IMPORTANT_DESTINATIONS(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR),
    SAVE_IMPORTANT_DESTINATIONS(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR),
    ADD_IMPORTANT_PACKAGES(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR),
    SAVE_IMPORTANT_PACKAGES(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR),
    
    TOUR_PACKAGE(RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    ADD_TOUR_PACKAGE(RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    DELETE_TOUR_PACKAGE(RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    TRANSFERS(RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    ADD_TRANSFERS(RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    DELETE_TRANSFERS(RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    HOTEL_RATES(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    PACKAGES(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    EDIT_CONFIG(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.EXPERT, RoleType.TOUR_OPERATOR, RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TRAVEL_AGENT),
    DELETE_CONFIG(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.EXPERT, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT),
    CONFIG(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.EXPERT, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT),
    SAVE_CONFIG(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.EXPERT, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT),
    EDIT_ITINERARY(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT, RoleType.TRAVEL_AGENT),
    SAVE_ITINERARY(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT, RoleType.TRAVEL_AGENT),
    SAVE_ITINERARY_CONFIG(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.EXPERT),
    ADD_PACKAGES(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    DELETE_PACKAGES(RoleType.TOUR_OPERATOR,  RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT, RoleType.TRAVEL_AGENT),
    ADD_HOTEL_RATES(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    DELETE_HOTEL_RATES(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    ADD_TOUR_PRICING(RoleType.TOUR_OPERATOR),
    ADD_UPGRADES(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    SAVE_UPGRADES(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    DELETE_UPGRADES(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    ADD_EXPERIENCE(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    SHOW_EXPERIENCE(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    SAVE_EXPERIENCE(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    DELETE_EXPERIENCE(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    ADD_TRIP(RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    SAVE_TRIP(RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    DELETE_TRIP(RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    ADD_DEALS(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    SAVE_DEALS(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    DELETE_DEALS(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.TRAVEL_AGENT, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    DELETE_TOUR_PRICING(RoleType.TOUR_OPERATOR),
    MANAGE_TOUR_PRICING(RoleType.TOUR_OPERATOR),
    ADD_FIXED_PACKAGES(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    DELETE_FIXED_PACKAGE(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    CONFIGURE(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    PRICE_GRID(RoleType.ADMIN, RoleType.CALLCENTER, RoleType.TOUR_OPERATOR,  RoleType.HOTELIER, RoleType.GUEST_HOUSE),
    CONTRIBUTE,
    ADD_KR_RULES(RoleType.TOURISM_BOARD, RoleType.AIRPORT),
    DELETE_KR_RULES(RoleType.TOURISM_BOARD),
    DELETE_SHOPPINGFLOW(RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRLINE),
    DELETE_ADVISE(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.ADMIN, RoleType.AIRPORT, RoleType.CALLCENTER, RoleType.EXPERT),
    ADD_ADVISE(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.ADMIN, RoleType.CALLCENTER, RoleType.EXPERT, RoleType.AIRPORT, RoleType.TRAVEL_AGENT),
    EDIT_ADVISE(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.ADMIN, RoleType.CALLCENTER, RoleType.EXPERT, RoleType.TRAVEL_AGENT),
    VIEW_EXPERT_ADVISE(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT, RoleType.AIRPORT, RoleType.TRAVEL_AGENT),
    ADD_EXPERT_ADVISE(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT, RoleType.AIRPORT, RoleType.TRAVEL_AGENT),
    EDIT_CR(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRPORT, RoleType.EXPERT),
    DELETE_CR(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRPORT, RoleType.EXPERT),
    ADD_CR(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.AIRPORT, RoleType.EXPERT),
    DELETE_TRIP_FLOW(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.ADMIN, RoleType.AIRLINE),
    ADD_TRIP_FLOW(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.ADMIN, RoleType.AIRLINE),
    EDIT_TRIP_FLOW(RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.ADMIN, RoleType.AIRLINE),
    VIEW_TRIP_FLOW(RoleType.ADMIN),
    EDIT_KR_RULES(RoleType.TOURISM_BOARD, RoleType.AIRPORT),
    VIEW_KR_RULES(RoleType.TOURISM_BOARD, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.AIRPORT),
    VIEW_ADVISE(RoleType.TOURISM_BOARD, RoleType.ADMIN, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.TOUR_OPERATOR, RoleType.AIRPORT, RoleType.CALLCENTER),
    LOAD_CONTENT(RoleType.ADMIN, RoleType.CALLCENTER),
    LOAD_KRS(RoleType.ADMIN, RoleType.CALLCENTER),
    EDIT_CONTENT(RoleType.ADMIN, RoleType.CALLCENTER),
    SAVE_CONTENT(RoleType.ADMIN, RoleType.CALLCENTER),
    ADD_HOTEL_ALIAS(RoleType.ADMIN, RoleType.CALLCENTER),
    
    VIEW_PRODUCTS(RoleType.SUPPLIER, RoleType.PRODUCT, RoleType.PRODUCT_HEAD), //
    VIEW_PRODUCT(RoleType.SUPPLIER, RoleType.PRODUCT, RoleType.PRODUCT_HEAD), //

    UPDATE_PRODUCT_PRICING(RoleType.SUPPLIER), //
    UPDATE_ALLOWED_PRICING(RoleType.PRODUCT, RoleType.PRODUCT_HEAD),//
    
    TRUST_REQUESTS(RoleType.ADMIN, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT, RoleType.TRAVEL_AGENT, RoleType.AIRLINE), //
    SEND_TRUST_REQUESTS(RoleType.ADMIN, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT, RoleType.TRAVEL_AGENT, RoleType.AIRLINE), //
    RESEND_ALL_TRUST_REQUESTS(RoleType.ADMIN, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT, RoleType.TRAVEL_AGENT, RoleType.AIRLINE), //
    SAVE_TRUST_REQUEST(RoleType.ADMIN, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT, RoleType.TRAVEL_AGENT, RoleType.AIRLINE), //

    TRAVEL_TIPS(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), //
    ADD_TRAVEL_TIP(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), //
    SAVE_TRAVEL_TIP(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), //
    DELETE_TRAVEL_TIP(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), //
    
    PRODUCT_TRENDS(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), //
    GEO_PRODUCT_TRENDS(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), //
    REPRICE_PACKAGE, //
    BOOKING_SUMMARY, //
    BOOKING_SUMMARY_INSTANT, //
    PRODUCT_QUERY_PERFORMANCE_TRENDS(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), // 
    PRODUCT_QUERY_POSITION_TRENDS(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), //
    MY_BOOKINGS(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT, RoleType.AIRLINE), //
    PRODUCT_RANKING_IMPROVEMENT(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), //
    ATTACH_OFFER(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), //
    SAVE_ATTACHED_OFFER(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT), //
    REMOVE_ATTACHED_OFFER(RoleType.TRAVEL_AGENT, RoleType.TOUR_OPERATOR, RoleType.HOTELIER, RoleType.GUEST_HOUSE, RoleType.EXPERT); //

    // COPY_PRICING from Another items ?

    RoleType[] roleType = null;

    private PartnerAction(RoleType... roleType) {
        this.roleType = roleType;
    }

    public String getActionName() {
        return this.name();
    }

    public boolean requireSecureConnection() {
        return false;
    }

    public boolean needsRefererCheck() {
        return false;
    }

    public String[] getAllowedRoles() {
        return null;
    }

    public RoleType[] getAllowedRoleTypes() {
        return roleType;
    }

    public boolean requireLogin() {
        return false;
    }

}
